terraform:
- changed-files:
  - any-glob-to-any-file: terraform/**

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

ci:
- changed-files:
  - any-glob-to-any-file: '.github/**'

feature:
 - head-branch: ['^feature', 'feature']

release:
 - base-branch: 'main'
