formatter: markdown table

recursive:
  enabled: true
  path: ./modules
  include-main: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  show:
    - providers
    - modules
    - inputs
    - outputs

sort:
  enabled: true
  by: required

# settings:
#   anchor: true
#   color: true
#   default: true
#   description: false
#   escape: true
#   hide-empty: false
#   html: true
#   indent: 2
#   lockfile: true
#   read-comments: true
#   required: true
#   sensitive: true
#   type: true
