name: Generate terraform docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_find_dir: modules/
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'
